version: '3.8'

services:
  app:
    build:
      context: ./backend-flottee
      dockerfile: Dockerfile
    container_name: flottee-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend-flottee:/var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
